// <auto-generated />
using API.Basket;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations.BasketItem
{
    [DbContext(typeof(BasketItemContext))]
    [Migration("20191121195712_BasketItems")]
    partial class BasketItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Basket.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Closed");

                    b.Property<string>("CustNumber");

                    b.Property<decimal>("Price");

                    b.Property<int>("ProdId");

                    b.Property<string>("ProductBrand");

                    b.Property<decimal>("Qty");

                    b.HasKey("Id");

                    b.ToTable("BasketItems");
                });
#pragma warning restore 612, 618
        }
    }
}
